### ISSUE TITLE
Missed syntax error for trailing commas in record declaration

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#123]
```powerquery
Connector = [
    TestConnection = (dataSourcePath) => { "Foo.Contents", dataSourcePath },
    Authentication = [
        AuthRecord = [
            AuthorizationUri = (resource) => FunctionCall(),
        ],
    ]
];
```

should report syntax errors for trailing `,` after `AuthorizationUri` line, and `AuthRecord` declaration.

**Comment by JordanBoltonMN** [comment]
On master this does report an error about a dangling comma. Can you re-confirm this is an issue for you when using the latest version?

**Comment by JordanBoltonMN** [comment]
Confirmed with Matt that it was another package using an outdated parser. Closing as fixed.
