### ISSUE TITLE
Scoping to Specific Language Components

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/powerquery-parser#142]
Hello,

Is there an easy way to scope lexing/parsing so that it is performed relative to a specific language component? In other words, when passing in a string for lexing/parsing, is there an easy way to say "this should be _x_" (where _x_ might be a `regular-identifier`, a `quoted-identifier`, an `expression-document`, a `section-document`, etc.) and then have the lexer/parser only consider the input valid if it complies with the expected syntax for _x_?

So, for example, if `section A; shared Query1 = true;` is lexed/parsed as an `expression-document`, the result should be an error because the input, while valid M code, is not an `expression-document`.

Thank you,
Ben

**Comment by JordanBoltonMN** [comment]
Currently there is not, it's an all-or-nothing approach. I've thought about adding in that functionality before, but personally didn't have a need for it. @bgribaudo can you tell me what your use case scenario is?

**Comment by bgribaudo** [comment]
Sure! 

The [DataMashup Cmdlets](https://bengribaudo.com/tools/datamashupcmdlets) allow (among other things) section members to be renamed & deleted. Also, the expression associated with a section member can be replaced. Member names and replacement expressions are both validated, currently using Anltr4.

Antlr4 allows parsing to start relative to a given rule. This allows the cmdlets to request parsing/validation using the correct rules for kind of input that was provided (e.g. if the user provides an expression for a section member, `expression` syntax should be allowed but not a full `section-document`, so the input should be validated relative to the rule for `expression`).

**Comment by JordanBoltonMN** [comment]
I don't think that would be a problem. There is a shared IParser interface which contains most productions as methods. I think we could add a `start` method which by default would be the read section/expression behavior, but could be overwritten.


How does this look for setting a parser that starts reading an IfExpression?
```
const customParser: IParser = {
    ...CombinatorParser,
    start: CombinatorialParser.readIfExpression
}
```

**Comment by bgribaudo** [comment]
Thank you, @JordanBoltonMN!

I'm not a JavaScript expert, but it looks like that would work.

> Edit: also let me know if you're looking for a specific production not listed under IParser.ts

For my purposes, I'd be looking for:
* section document (which I see in IParser.ts)
* expression document (IParser.ts contains `readExpression` -- will that ensure that the entire input is an expression document or just that the input starts with a valid expression but may be followed by other valid or invalid content?)
* regular identifier
* quoted identifier (with my current parsing/validation strategy, I use this and the proceeding to determine whether to write out a given identifier verbatim or as a quoted identifier, or whether to reject it as invalid)

**Comment by JordanBoltonMN** [comment]
I merged #148 which should work for your goals. Take a look at [this test case](https://github.com/microsoft/powerquery-parser/blob/master/src/test/libraryTest/parser/simple.ts#L111) for how to specify what the parser should start reading on. After parsing it will do the usual validation that no tokens remain.

A note about identifiers. To the AST there is no difference between quoted identifiers or non-quoted identifiers. Both are stored as an Identifier token. If you want to know if it's quoted or not you'll need to check if the string begins with a `#` or not.

Let me know if you have any comments/questions/concerns.

**Comment by bgribaudo** [comment]
That was fast! Thank you very much, @JordanBoltonMN!

> A note about identifiers. To the AST there is no difference between quoted identifiers or non-quoted identifiers. Both are stored as an Identifier token. If you want to know if it's quoted or not you'll need to check if the string begins with a # or not.

Thanks for the pointer. As far as this parser/the AST goes, are generalized-identifiers different, so not matched by readIdentifier?

**Comment by JordanBoltonMN** [comment]
Generalized identifiers and identifiers are different. To get a generalized identifier you would use `IParser.readGeneralizedIdentifier`.

Generally speaking, think of generalized identifiers as things that could be column names / record keys, and identifiers as names of things in your M code.

**Comment by bgribaudo** [comment]
Thanks for confirming, @JordanBoltonMN. Treating them as a separate concept makes sense and is what I've been doing/what I need--just wanted to make sure that this was what was going on here.

I was trying to test/verify how generalized-identifiers were handled myself yesterday but was got stuck because Visual Studio kept aborting the script (turns out a `UnusedTokensRemainError` error was being raised which I wasn't seeing it in the UI). 

This exception raises a question. :-)

When a token that different from what is expected is encountered, `triedLexParse` returns an error. On the other hand, if tokens remain after parsing consumes all that it expects, an exception is raised (`UnusedTokensRemainError`). For symmetry's sake, would it make sense for unused tokens to also result in an error vs. raising an exception?

Example:
* If I try to parse "1" as an identifier an error with the message "Expected to find a identifier, but a numeric literal was found instead" is returned.
* If I try to parse "a b" as an identifier, `UnusedTokensRemainError` is raised. Would it make sense for this to instead be an error like "Unused tokens remain"?

````
const customParser: IParser<IParserState> = {
    ...RecursiveDescentParser,
    read: RecursiveDescentParser.readIdentifier,
};
const customSettings: Settings = {
    ...DefaultSettings,
    parser: customParser,
};
const triedLexParse: Task.TriedLexParse = Task.tryLexParse(
    customSettings,
    "1", // "a b",
);
````

**Comment by JordanBoltonMN** [comment]
Embarrassing, it throwing is a mistake not a design choice. I created a new version where it'll return a Result<UnusuedTokensRemainError>. @bgribaudo I'll push out a new version today.

**Comment by bgribaudo** [comment]
Thank you, @JordanBoltonMN. I just tested the new version and now receive an error when unused tokens remain.
