### ISSUE TITLE
C# Interop

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/powerquery-parser#143]
Hello,

I'm currently parsing M using Antlr4. Replacing this with a parser backed by Microsoft is very, _very_ interesting to consider. However, my application is written in C#/.Net Core while this project is TypeScript/JavaScript-based. 

I'm curious if there are others out there who have set up JS<->C# interop with this parser, and, if so, what technique you found worked well for doing this (e.g. using something like [Jint](https://github.com/sebastienros/jint), spinning up a local Node.js web server. etc.). I would be most grateful for any tips you might want to share.

Thank you,
Ben

**Comment by mattmasson** [comment]
One of the main motivators for this project was to avoid the JS <-> C# interop. 

Power Query does its JS <-> C# interaction through a browser control (the frontend UI is HTML/JS, and the backend is C#)... which is harder for us to do in VS Code and Power Query Online.

**Comment by bgribaudo** [comment]
Thanks, @mattmasson!
