### ISSUE TITLE
IntelliSense Support

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/powerquery-parser#151]
Am I correctly getting the sense that there are plans to extend this library to provide support for code editor IntelliSense uses? :-)

/ Related #60 

Ben

**Comment by JordanBoltonMN** [comment]
You are correct. We are currently working on a new Power Query extension which will use this parser as it's base. I can @you when it's released.

**Comment by bgribaudo** [comment]
Thank you, @JordanBoltonMN. Much appreciated. 

(Just an idea: It would be really neat if the new extension packaged the list of IntelliSense member definitions it uses in a way that could be easily extracted and used by other tools....)

**Comment by mattmasson** [comment]
@bgribaudo - there are two projects you might be interested in;

- PQ/M VS Code extension: https://github.com/microsoft/vscode-powerquery/
- Language Services library: https://github.com/microsoft/powerquery-language-services/

vscode-powerquery has a [.json file](https://github.com/microsoft/vscode-powerquery/blob/master/server/src/library/standard.json) that contains a hardcoded list of M library symbols. However, I expect I'll be changing the existing file format in the near future. Ultimately I'd like this to be dynamically retrieved from an M backend service, but until then we'll be keeping this up to date. 

[powerquery-language-services](https://github.com/microsoft/powerquery-language-services/) provides the Language Server Protocol capabilities, and relies heavily on the powerquery-parser code. This is where you'd find most of the "intellisense" functionality.

Contributions are welcome! If you're looking for ideas of where to help out, feel free to reach out!

**Comment by bgribaudo** [comment]
Thank you, @mattmasson (and @JordanBoltonMN)!
