### ISSUE TITLE
[BUG] Invalid Syntax Accepted for Generalized Identifiers

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/powerquery-parser#152]
**Expected behavior**
generalized-identifiers of "a{new line character}b" and "a/*hi*/b" should be rejected because they don't comply with the [appropriate syntax rules](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#identifiers) in the Power Query language specification.

**Actual behavior**
Both of the above identifiers are accepted as valid.

**To Reproduce**
````
const customParser: IParser<IParserState> = {
    ...RecursiveDescentParser,
    read: RecursiveDescentParser.readGeneralizedIdentifier,
};
const customSettings: Settings = {
    ...DefaultSettings,
    parser: customParser,
};
const triedLexParse: Task.TriedLexParse = Task.tryLexParse(
    customSettings,
    `a
b`
    // or 'a/*hi*/b'
); // expect the result to be an error; currently, an ok result is being returned
````

**Additional context**
If I'm understanding the language specification correctly, a `generalized-identifier` is made up of one or more (`keyword-or-identifier` or decimal-digit + `keyword-or-identifier`) segments, separated by dots (.) or blanks (e.g. spaces). 

In turn, the only characters allowed in `keyword-or-identifier` are letters, numbers and underscores plus connecting, combining and formatting characters. Turning this list into a regular expression (using the specific character classes listed in the spec) produces the following: `[\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Mn}\p{Mc}\p{Pc}\p{Cf}\p{Nd}_]`

`\n`, `/` and `*` all do not match this regex so I believe should be rejected as invalid `generalized-identifier` syntax.

(Note: The above regex tests valid characters allowed in a `keyword-or-identifier`; however, for simplicity, it does not check whether the identifier's starting character matches the rules for the starting character given in the spec.

**Comment by JordanBoltonMN** [comment]
This is an spec vs implementation issue. You are correct that the parser doesn't match the spec. Originally the implementation matched the the spec but ran into problems (#78). After that change went through the deviation was marked in the [specification.md](https://github.com/microsoft/powerquery-parser/blob/master/specification.md).

The solution I ended up on was to just copy the implementation of the official C# parser.

**Comment by bgribaudo** [comment]
Hi @JordanBoltonMN,

Thanks for the fast response.

Do you know if there are any plans to align the spec with the C# parser's behavior? I've run into a number of other deviations (I have several issues open over at https://github.com/MicrosoftDocs/powerquery-docs/issues and have a few more that I haven't added to that list yet). It's hard to write things that interoperate when the spec defining how to interoperate isn't the full authority on the matter. :-)

On these two particular cases, though, Excel's Query Editor rejects both as having syntax errors:

````
a[a/*hi*/b]
````
 // Expression.SyntaxError: Invalid identifier.

````
a[a
b]
````
 
// Expression.SyntaxError: Invalid identifier.

I'm confused on the expected behavior here, since from your comments above it sounds like these should be valid. Is Excel using the C# parser but with some additional rules in place?

**Comment by JordanBoltonMN** [comment]
I see the issue. Later on in the C# parser there is a check if it's a valid generalized-identifier, or rather a check that's /close/ to a generalized-identifier. I'll aim to put out an update soon which will add the missing check.

For what it's worth we very much do appreciate you bringing up these issues. Sometimes things get lost in the shuffle, and for every person who brings up an issue there's several more who experience the problem and never mention it to us :)

**Comment by bgribaudo** [comment]
Thank you for the kind words, Jordan, and for the module update.

I tested the new version and both cases now error (good!). 

Regarding the error message returned: 

If I try to parse a non-general identifier (`readIdentifier`) and the text to parse contains extraneous content (e.g. "a b") the error message returned says "Finished parsing but more tokens remain". This implies (correctly) that one or more tokens were matched as satisfying the specified rule but then one or more (unexpected) tokens remain. 

However, when I try either of the above generalized-identifier test cases, the error returned is "Expected to find a generalized identifier but the end-of-stream was reached first", which makes it sound like the input was blank. In actuality, part of the input was a valid generalized identifier; the problem was the fact that the input contained extra content beyond what was expected/valid.  

Is it worth aligning these two error messages or is this getting into splitting hairs? :-)
