### ISSUE TITLE
Inspection.Autocomplete should contain types and type modifiers

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#161]
**Expected behavior**
I'd expect built-in types to be included in the autocomplete list in these cases: 

`(param as |`
`value is |`
`Table.AddColumn(table, "Column", each null, type |)`

Also applies to places where `optional` and `nullable` would show up.

**Comment by mattmasson** [comment]
Closed by accident!

**Comment by mattmasson** [comment]
Discussion summary:

- Rename `Inspection.autocomplete` member to `Inspection.validLanguageConstants`
- Member could be something like an array of `<KeywordKind | PrimitiveTypeConstantKind | IdentifierConstantKind>` 
- Update autocomplete logic to include primitive types and identifier constants

**Comment by JordanBoltonMN** [comment]
This was resolved over several PRs. Autocomplete now has several attributes, one per autocomplete pass, such as; field access, language constants, etc.
