### ISSUE TITLE
[Enhancement] Support for custom M-extensions

### ISSUE THREAD

**Issue by ImkeF** [microsoft/powerquery-parser#169]
It would be great if the VS Code extension would support custom M-extensions with own functions as well.

**Comment by ninmonkey** [comment]
You can with the brand new VS Code extension

- https://github.com/microsoft/vscode-powerquery-sdk

**Comment by mattmasson** [comment]
closing this out - this is functionality provided at the vscode-powerquery and vscode-powerquery-sdk levels rather than the underlying parser.
