### ISSUE TITLE
Parser error when function return type is nullable

### ISSUE THREAD

**Issue by UliPlabst** [microsoft/powerquery-parser#199]
I recently got a bug report for my powerquery formatter which I tracked down to occur in the parser library. You can have a look at the original issue [here](https://github.com/mogular/powerquery-formatter-examples/issues/13).   
The minimal code to reproduce the issue is:
```powerquery
let
    Fn = () as nullable text => "asd"
in
    Fn
``` 
Everything works fine if the function return type is not specified nullable. But with the nullable key word an exception is thrown by the parser:
```
Error: InvariantError: cannot delete Ast if it has children - {
    "nodeId": 8,
    "childIds": [
        10
    ]
}
```
Stack: 
```
 at new CommonError (.\node_modules\@microsoft\powerquery-parser\lib\common\error.js:23:28)
    at Object.ensureCommonError (.\node_modules\@microsoft\powerquery-parser\lib\common\error.js:84:16)
    at Object.tryRead (.\node_modules\@microsoft\powerquery-parser\lib\parser\IParser\IParserUtils.js:19:51)
    at tryParse (.\node_modules\@microsoft\powerquery-parser\lib\task.js:37:34)
    at Object.tryLexParse (.\node_modules\@microsoft\powerquery-parser\lib\task.js:74:22)
    at Object. (.\dist\formatter.js:47:47)
    at Generator.next ()
    at .\node_modules\tslib\tslib.js:114:75
    at new Promise ()
    at Object.__awaiter (.\node_modules\tslib\tslib.js:110:16)
```
I could not find anything in the [powerquery function documentation](https://docs.microsoft.com/en-us/powerquery-m/understanding-power-query-m-functions) or the [consolidated grammar](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar) that would indicate that nullable return types are prohibited for functions.

**Comment by JordanBoltonMN** [comment]
Thanks for the find. You are correct that functions should be able to have nullable primitive types, and this is indeed a problem with the parser. In fact you should treat any InvariantError which leaves the parser's internals as a bug. They're the parser's versions of asserts.

I'll try to get a look at this issue sometime in the next few days.

**Comment by JordanBoltonMN** [comment]
Actually, I ended up having some unexpected free time today, and merged #200 .

The issue ended up being something completely unrelated to function expressions. The cause was due to an improperly sorted array of numbers. It was using JavaScript's default behavior of alphabetically sorting the array of numbers, not numeric sorting them as expected.

As a side note, let me know if you have some time to talk about your usage of the parser. I'm curious to hear feedback from someone else who is consuming this library.

**Comment by UliPlabst** [comment]
Thank you for the fix, I already deployed the fix with the new parser version and everything is working now.   
Sometimes javascript still gets you even though typescript fixes a lot of it's issues :)  
  
I actually have some spare time today or tomorrow/friday. What would be the appropriate format to talk? Via E-Mail? I'm in Timezone CET so I'm usually at work from 07:00 UTC to 15:00 UTC.

**Comment by JordanBoltonMN** [comment]
@UliPlabst Let's start with email since I'll out of the office with limited internet starting Saturday. You can email me at `${firstname}${lastname}@microsoft.com`. My GitHub username has my first and last name once you drop `MN`.

**Comment by UliPlabst** [comment]
@JordanBoltonMN  Ok so I sent a mail to the address but office365 replied it couldn't find you (yes, I dropped `MN`). I just sent you an E-Mail to the address I found in `git log`. Hope you don't mind.
