### ISSUE TITLE
Improve API for moving from TriedParse to TriedInspect

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#50]
It would be nice if we could easily go from a `TriedParse` to a `TriedInspect`. We currently have to check the parse results and take either `TriedParse.value` or `TriedParse.error.context`. I had to create an intermediate `Inspectable` interface to unify the code paths.

Most intellisense operations that require `Inspect` won't care whether the parse succeeded without errors. 

```typescript
interface Inspectable {
    nodeIdMapCollection: PQP.NodeIdMap.Collection;
    leafNodeIds: ReadonlyArray<number>;
}

const triedParser: PQP.Parser.TriedParse = PQP.Parser.tryParse(triedSnapshot.value);
let inspectableParser: Inspectable | undefined;
if (triedParser.kind === PQP.ResultKind.Ok) {
    inspectableParser = triedParser.value;
} else if (triedParser.error instanceof PQP.ParserError.ParserError) {
    inspectableParser = triedParser.error.context;
}

```

**Comment by JordanBoltonMN** [comment]
I'm thinking the best approach is to add a helper function in jobs.ts, similar to tryLexAndParse. Maybe a function named `tryLexParseInspect`?
