### ISSUE TITLE
Inspect - identify when position is left hand side of assignment

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#56]
We shouldn't return intellisense suggestions when we're on the left hand side of an assignment (i.e. providing a variable name). Ex:

`let a = 1, |`
`let a = 1, bin|`

Ideally, the inspection result would provide a boolean flag that the intellisense code would use to determine that no suggestions should be returned in these cases.

**Comment by mattmasson** [comment]
@JordanBoltonMN - thoughts/suggestions on how to best implement this? Would I check if the closest node is a Constant(`,`), but **not** a parameter for an invoke expression?

**Comment by JordanBoltonMN** [comment]
I see a few scenarios considering the inspection finds the closest leaf node to the left of the cursor, then travels upwards through its parents:

* If you reach a GeneralizedIdentifierPairedExpression, then you must be in a RecordExpression. When in a record expression you either are or are not on the key
* If you reach a GeneralizedIdentifierPairedAnyLiteral, then you must be in a RecordLIteral. When in a record literal you either are or are not on the key.
* If you reach a LetExpression, then you may be in a LetExpression. First check if the parent is a LetExpression, then check if you are either are or are not on the key.

**Comment by JordanBoltonMN** [comment]
Resolved in #70 and #76
