### ISSUE TITLE
Inspect - provide an easy way to determine type/additional info about scope members

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#60]
Intellisense will use the `scope` to determine additional completion items to include in the suggestion list. Ideally we'd be able to display the correct type in addition to its name/label (function, numeric literal, string literal, etc).

**Comment by mattmasson** [comment]
I think a simple way to do this would be to store the `IdentifierPairedExpression` node rather than the `Identifier` node when adding let and section members to the scope.

**Comment by JordanBoltonMN** [comment]
The first step was #122 .

**Comment by JordanBoltonMN** [comment]
Completed with #156
