### ISSUE TITLE
Inspect - provide list of valid/expected keywords for position

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#62]
I've recently added M keywords to intellisense suggestions. It would be great if the inspection class returned a list of expected keywords for the current position. 

ex. `shared a = |`

should include keywords like `let` and `if`, but not `else` or `otherwise` ...

**Comment by JordanBoltonMN** [comment]
Initial work done with #85 . Future needed work will be considered its own task/bug.
