### ISSUE TITLE
Grammar in Antlr or Irony

### ISSUE THREAD

**Issue by sjahongir** [Microsoft/powerquery-parser#7]
Can you provide lexer and parser (grammar) in **[Antlr](https://www.antlr.org/)** or **[Irony](https://archive.codeplex.com/?p=irony)**?

I need to write a parser in C#

**Comment by mattmasson** [comment]
We currently don't plan to create Antlr or Irony grammars for the language, but a TextMate grammar can be found in the [powerquery-language](https://github.com/Microsoft/powerquery-language) project. 

Out of curiosity - what will the C# parser be used for?

**Comment by sjahongir** [comment]
I want to create my own scripting language like Power Query.

**Comment by mattmasson** [comment]
Sorry, can't help you there.
