### ISSUE TITLE
Support for localized parser/lexer error messages

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#77]
To be able to consume this library in PQ clients, we'll need to support full localization of the error messages raised by the parser/lexer. 

We should probably review the format of the messages before we submit for localization.

**Comment by JordanBoltonMN** [comment]
It's up to the host to implement localization. All messages default to the built-in en-US localization. A host can decide to change any/all error message by providing a custom localization template. There are many presets placed in `src/localization/templates`.
