### ISSUE TITLE
#nan inside of if then clause results in parser error

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#80]
```
if [str] = "nan" then
    #nan
else if [str] = "+inf" then
    #infinity
else if [str] = "-inf" then
    -#infinity
else
    Double.From([str], "en-us")
```

Expected to find one of the following on line 2, column 5, but a KeywordHashNan was found instead: [HexLiteral,KeywordFalse,KeywordTrue,NumericLiteral,NullLiteral,StringLiteral].

**Comment by JordanBoltonMN** [comment]
The problem is #nan isn't considered an expression. The why is probably because it's not being considered as a numeric literal. I'll investigate why.
